#!/usr/bin/env python3
"""Generate <product_root>/data-dictionary.md — a read-only view assembled from the owners' files.

  python3 scripts/data_dictionary.py --product-root docs/product           # write
  python3 scripts/data_dictionary.py --product-root docs/product --check   # exit 1 when stale or hand-edited
  python3 scripts/data_dictionary.py --self-test

Each fact keeps one owner; the dictionary only joins them:
  structure  erd.dbml (dba)             tables, columns, types, constraints, column notes, "一行 = …"
  meaning    domain-model.md §2 (dba)   the glossary row whose 代码 / 表名 cell names the table
  metrics    data/metrics.yaml (dw)     id, name, formula, source events, owner, FR anchor
Gaps are listed rather than filled in: a table without a glossary term, a term naming a missing table.
Sources still carrying sdlc:unfilled are skipped and reported.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "diagram"))
from semantic import table_blocks  # noqa: E402  (one DBML table parser for the dictionary and the diagram gate)

HEADER = "<!-- GENERATED by scripts/data_dictionary.py — do not edit; change the sources and regenerate -->"
UNFILLED = re.compile(r"^[ \t]*(<!--|#|//)[ \t]*sdlc:unfilled", re.M)
SOURCES = ("erd.dbml", "domain-model.md", "data/metrics.yaml")


def sha(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()[:16]


def cell(s: str) -> str:
    return str(s).replace("|", "\\|").replace("\n", " ")


def parse_tables(dbml: str) -> list[dict]:
    tables = []
    for raw, body in table_blocks(re.sub(r"//[^\n]*", "", dbml)):
        name = raw.strip('"').split(".")[-1]
        body_no_idx = re.sub(r"^\s*indexes\s*\{.*?^\s*\}", "", body, flags=re.M | re.S)
        note = re.search(r"^\s*Note\s*:\s*'([^']*)'", body_no_idx, re.M | re.I)
        cols = []
        for line in body_no_idx.splitlines():
            line = re.sub(r"//.*", "", line).strip()
            if not line or re.match(r"(?i)note\s*:", line):
                continue
            cm = re.match(r"\"?(\w+)\"?\s+([\w()., ]+?)\s*(?:\[(.*)\])?$", line)
            if not cm:
                continue
            attrs = cm.group(3) or ""
            cnote = re.search(r"note\s*:\s*'([^']*)'", attrs, re.I)
            flags = [a.strip() for a in re.sub(r"note\s*:\s*'[^']*'", "", attrs, flags=re.I).split(",") if a.strip()]
            cols.append({"name": cm.group(1), "type": cm.group(2).strip(), "flags": ", ".join(flags), "note": cnote.group(1) if cnote else ""})
        tables.append({"name": name, "row": note.group(1) if note else "", "columns": cols})
    return tables


def parse_glossary(md: str) -> list[dict]:
    sec = re.search(r"^##\s*2\..*?$(.*?)(?=^##\s)", md, re.M | re.S)
    rows = []
    for line in (sec.group(1) if sec else "").splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 5 or cells[0] in ("术语", "") or set(cells[0]) <= set("-: "):
            continue
        rows.append({"term": cells[0], "definition": cells[1], "code": cells[2], "context": cells[4],
                     "tables": re.findall(r"`([\w]+)`", cells[2])})
    return rows


def parse_metrics(yaml_text: str) -> list[dict]:
    out, cur = [], None
    for line in yaml_text.splitlines():
        m = re.match(r"^\s*-\s+id:\s*(\S+)", line)
        if m:
            cur = {"id": m.group(1)}
            out.append(cur)
            continue
        m = re.match(r"^\s{2,}(\w+):\s*(.*?)\s*(?:#.*)?$", line)
        if cur is not None and m:
            cur[m.group(1)] = m.group(2).strip().strip('"')
    return out


def build(product_root: Path) -> tuple[str, list[str]]:
    notes, texts = [], {}
    for rel in SOURCES:
        p = product_root / rel
        if not p.is_file():
            notes.append(f"{rel} 不存在")
        elif UNFILLED.search(p.read_text(encoding="utf-8", errors="replace")[:4000]):
            notes.append(f"{rel} 仍是模板（sdlc:unfilled），未纳入")
        else:
            texts[rel] = p.read_text(encoding="utf-8", errors="replace")
    tables = parse_tables(texts.get("erd.dbml", ""))
    gloss = parse_glossary(texts.get("domain-model.md", ""))
    metrics = parse_metrics(texts.get("data/metrics.yaml", ""))
    by_table = {t: g for g in gloss for t in g["tables"]}
    L = [HEADER, "<!-- sources: " + " ".join(f"{k}={sha(v)}" for k, v in sorted(texts.items())) + " -->", "", "# 数据字典", "",
         "> 生成视图。结构来自 `erd.dbml`，业务含义来自 `domain-model.md` §2 统一语言，指标来自 `data/metrics.yaml`。"
         "要改内容，改对应的来源文件后重新生成。", ""]
    if notes:
        L += ["**未纳入的来源：** " + "；".join(notes), ""]
    L += ["## 1. 表与字段", ""]
    for t in tables:
        g = by_table.get(t["name"])
        L += [f"### `{t['name']}`" + (f" · {g['term']}" if g else ""), ""]
        facts = ([f"- 一行 = {t['row'].replace('一行 = ', '')}"] if t["row"] else []) + \
                ([f"- 含义（统一语言）：{g['definition']}（上下文：{g['context']}）"] if g else [])
        L += facts + ([""] if facts else [])
        L += ["| 字段 | 类型 | 约束 | 说明 |", "|---|---|---|---|"]
        L += [f"| `{c['name']}` | {cell(c['type'])} | {cell(c['flags'])} | {cell(c['note'])} |" for c in t["columns"]]
        L.append("")
    if metrics:
        L += ["## 2. 指标", "", "| id | 名称 | 层级 | 口径 | 来源事件 | 负责人 | 锚点 |", "|---|---|---|---|---|---|---|"]
        for m in metrics:
            L.append(f"| `{m['id']}` | {cell(m.get('name', ''))} | {cell(m.get('layer', ''))} | `{cell(m.get('formula', ''))}` | "
                     f"{cell(m.get('source_events', ''))} | {cell(m.get('owner', ''))} | {cell(m.get('fr_anchor', ''))} |")
        L.append("")
    gaps = [f"表 `{t['name']}` 在统一语言里没有术语" for t in tables if t["name"] not in by_table]
    names = {t["name"] for t in tables}
    gaps += [f"术语「{g['term']}」写的表 `{x}` 不在 erd.dbml" for g in gloss for x in g["tables"] if tables and x not in names]
    gaps += [f"指标 `{m['id']}` 缺负责人" for m in metrics if not m.get("owner")]
    L += ["## 3. 缺口（由各自负责人补齐，字典不代填）", ""] + ([f"- {x}" for x in gaps] or ["- 无"]) + [""]
    return "\n".join(L), notes


def self_test() -> int:
    with tempfile.TemporaryDirectory() as td:
        pr = Path(td)
        (pr / "data").mkdir()
        (pr / "erd.dbml").write_text("Table datasets {\n  id bigint [pk, increment]\n  source_type varchar(32) [not null, note: '扩展点']\n"
                                     "  indexes {\n    (id) [unique]\n  }\n  Note: '一行 = 一次导入'\n}\nTable orphans {\n  id bigint [pk]\n}\n")
        (pr / "domain-model.md").write_text("# 领域模型\n## 2. 统一语言（词汇表）\n\n| 术语 | 定义 | 代码 / 表名 | 禁用同义词 | 所属上下文 |\n|---|---|---|---|---|\n"
                                            "| 数据集 | 一次导入的数据 | `dataset` / `datasets` | 表格 | 数据接入 |\n| 报表 | 报表定义 | `reports` | — | 报表 |\n\n## 3. 聚合\n")
        (pr / "data/metrics.yaml").write_text("metrics:\n  - id: m1\n    name: 指标一\n    formula: \"COUNT(*)\"\n    owner: pm\n  - id: m2\n    name: 指标二\n")
        text, notes = build(pr)
        for want in ("`datasets` · 数据集", "一行 = 一次导入", "| `source_type` | varchar(32) | not null | 扩展点 |", "`m1`",
                     "表 `orphans` 在统一语言里没有术语", "术语「报表」写的表 `reports` 不在 erd.dbml", "指标 `m2` 缺负责人"):
            if want not in text:
                print("self-test FAILED: missing", want); return 1
        if "indexes" in text or "`(id)`" in text:
            print("self-test FAILED: index lines leaked into columns"); return 1
        (pr / "data-dictionary.md").write_text(text + "\n")
        if main(["--product-root", str(pr), "--check"]) != 0:
            print("self-test FAILED: a freshly written dictionary must be current"); return 1
        (pr / "erd.dbml").write_text((pr / "erd.dbml").read_text().replace("orphans", "orphans2"))
        if main(["--product-root", str(pr), "--check"]) != 1:
            print("self-test FAILED: a changed source must make the dictionary stale"); return 1
    print("self-test ok")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--product-root")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args(argv)
    if a.self_test:
        return self_test()
    if not a.product_root or not Path(a.product_root).is_dir():
        print("usage: data_dictionary.py --product-root <dir> [--check]", file=sys.stderr)
        return 2
    pr = Path(a.product_root)
    text, notes = build(pr)
    out = pr / "data-dictionary.md"
    if a.check:
        cur = out.read_text(encoding="utf-8") if out.is_file() else ""
        if cur.rstrip("\n") != text.rstrip("\n"):
            print(f"✗ {out} 与来源不一致（来源已变或被手改）：python3 scripts/data_dictionary.py --product-root {pr}")
            return 1
        print(f"✓ {out} 与来源一致")
        return 0
    out.write_text(text + "\n", encoding="utf-8")
    print(f"✓ 已生成 {out}" + (f"（未纳入：{'；'.join(notes)}）" if notes else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
