#!/usr/bin/env python3
"""Host manifests and the host reference, generated from adapters/hosts.json + workflow/registry.json.

Called by `workflow.py render` (generated_files), so `render --check` and health-check catch drift.
Why each file looks the way it does is recorded in adapters/HOST-NOTES.md:
- no root plugin.json: Grok reads it before .grok-plugin/ and would lose the explicit agent list;
- explicit agent lists: Claude Code and Grok scan agents/ recursively (agents/_lib, agents/profiles are sources);
- Codex has its own marketplace file: `policy` is required there but unknown to Claude Code (--strict fails).
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HOSTS_FILE = "adapters/hosts.json"
CODEX_AGENT_DIR = "adapters/codex/agents"


def load_hosts(root=ROOT):
    return json.loads((Path(root) / HOSTS_FILE).read_text(encoding="utf-8"))


def _json(value):
    return json.dumps(value, ensure_ascii=False, indent=2) + "\n"


def role_agent_files(registry):
    return [f"./agents/{role}.md" for role in registry["roles"]]


def codex_agent_name(hosts, role):
    return hosts["codex"]["agent_prefix"] + role


def _identity(plugin, *keys):
    return {k: plugin[k] for k in keys if k in plugin}


def zcode_manifest(hosts):
    p = hosts["plugin"]
    return {**_identity(p, "name", "version", "description", "description_i18n", "author", "keywords"),
            "skills": "skills", "commands": "commands", "agents": "agents"}


def claude_manifest(hosts, registry):
    # Claude Code and Grok share the format; both need the explicit list (recursive agents/ scan).
    p = hosts["plugin"]
    return {**_identity(p, "name", "version", "description", "author", "license", "repository", "keywords"),
            "agents": role_agent_files(registry)}


def claude_marketplace(hosts):
    p, m = hosts["plugin"], hosts["marketplace"]
    return {"name": m["name"], "owner": m["owner"], "description": m["description"],
            "plugins": [{"name": p["name"], "source": "./", "version": p["version"],
                         "description": p["description_i18n"]["en"], "category": m["category"]}]}


def codex_manifest(hosts):
    p = hosts["plugin"]
    return {**_identity(p, "name", "version", "description", "author", "license", "repository", "keywords"),
            "skills": "./skills/", "interface": hosts["codex"]["interface"]}


def codex_marketplace(hosts):
    p, m, c = hosts["plugin"], hosts["marketplace"], hosts["codex"]
    return {"name": m["name"], "interface": {"displayName": c["interface"]["displayName"]},
            "plugins": [{"name": p["name"], "source": {"source": "local", "path": "./"},
                         "policy": c["policy"], "category": c["category"]}]}


def render_host_reference(hosts, registry):
    rows = ["# Hosts (generated)", "",
            "<!-- GENERATED by scripts/workflow.py render from adapters/hosts.json and workflow/registry.json. -->", "",
            "The same skills, commands and role agents run on ZCode, Claude Code, Grok and Codex. Packets and state "
            "always name the logical role `sdlc-workflow:<role>`; only the spawn call uses the host's type below. "
            "Identify the host from the tools you have (a Skill tool and plugin agent types, or Codex's `spawn_agent`); "
            "when unsure, try the native role type first.", "",
            "| Host | Manifest | Commands | Spawn a hat as | Generic fallback | Invoke a procedure | Reviewer/qc read-only |",
            "|---|---|---|---|---|---|---|"]
    for h in hosts["hosts"]:
        rows.append(f"| {h['label']} | `{h['manifest']}` | {h['commands']} | `{h['role_type']}` | `{h['generic_type']}` "
                    f"| {h['skill_call']} | {h['read_only']} |")
    rows += ["",
             "## Spawning and fallback", "",
             "Spawn the native role type once. If the host reports an unknown type, spawn **once** as that host's generic "
             "type with the same packet; its first action reads `PLUGIN_ROOT/agents/<role>.md` and the primary SKILL.md. "
             "Record `host_spawn.<role>` with the host, the type tried and the fallback used. Never dispatch both forms. "
             "On Codex without linked role agents the fallback is the normal path; link them with "
             "`python3 PLUGIN_ROOT/scripts/link-codex.py --project <project root>` so reviewer/qc also get a "
             "read-only sandbox. With the generic fallback the read-only rule is only the packet's, so check the record's "
             "write observation before accepting a review.", "",
             "## Reference only", "",
             "Every host uses this plugin by reference to one source directory. Never run a command that copies it; "
             "a copy silently diverges from the source.", ""]
    rows += [f"- **{h['label']}**: {h['install']}." for h in hosts["hosts"]]
    rows += ["",
             "## PLUGIN_ROOT", "",
             "PLUGIN_ROOT is two directories above the **real path** of the running `SKILL.md` (the folder with "
             "`skills/`, `agents/`, `scripts/`). Resolve symlinks first (`realpath <SKILL.md>`): hosts reach the plugin "
             "through links, and Codex shows `~/.codex/skills/sdlc-workflow/<skill>/SKILL.md`, whose lexical parent is "
             "not the plugin. ZCode also exports `$ZCODE_PLUGIN_ROOT` to the shell; Claude Code (`CLAUDE_PLUGIN_ROOT`) "
             "and Grok (`GROK_PLUGIN_ROOT`) set theirs only for hooks and MCP servers. Pass the absolute PLUGIN_ROOT in "
             "every packet.", "",
             "## Commands on hosts without plugin commands", "",
             "Codex plugins carry skills only. Invoke the command's skill and state the mode in the request; the skill "
             "treats an explicit `mode:` (or the command name, such as `/sdlc-product`) exactly like the command.", "",
             "| Command | Skill | Mode | Codex request (pick the skill with `$` or `/skills`) |", "|---|---|---|---|"]
    for name, item in registry["commands"].items():
        rows.append(f"| `/{name}` | `sdlc-workflow:{item['skill']}` | `{item['mode']}` "
                    f"| `sdlc-workflow:{item['skill']}` + `mode: {item['mode']} <arguments>` |")
    rows += ["", "## Role agents per host", "",
             "| Role | ZCode / Claude Code / Grok | Codex (linked) | Read-only |", "|---|---|---|---|"]
    for role, meta in registry["roles"].items():
        rows.append(f"| {role} | `sdlc-workflow:{role}` | `{codex_agent_name(hosts, role)}` | {'yes' if meta['fresh'] else 'no'} |")
    return "\n".join(rows) + "\n"


def render_hosts(registry, root=ROOT):
    hosts = load_hosts(root)
    yield ".zcode-plugin/plugin.json", _json(zcode_manifest(hosts))
    yield ".claude-plugin/plugin.json", _json(claude_manifest(hosts, registry))
    yield ".claude-plugin/marketplace.json", _json(claude_marketplace(hosts))
    yield ".grok-plugin/plugin.json", _json(claude_manifest(hosts, registry))
    yield ".codex-plugin/plugin.json", _json(codex_manifest(hosts))
    yield ".agents/plugins/marketplace.json", _json(codex_marketplace(hosts))
    yield "skills/sdlc/references/hosts.md", render_host_reference(hosts, registry)


def host_problems(registry, root=ROOT):
    """Structural rules the generated files cannot express by themselves."""
    root = Path(root)
    problems = []
    hosts = load_hosts(root)
    if (root / "plugin.json").exists():
        problems.append("plugin.json at the plugin root: Grok reads it before .grok-plugin/ and drops the explicit agent list")
    for rel in role_agent_files(registry):
        if not (root / rel).is_file():
            problems.append(f"listed agent missing: {rel}")
    if {h["id"] for h in hosts["hosts"]} != {"zcode", "claude", "grok", "codex"}:
        problems.append("adapters/hosts.json hosts must describe zcode, claude, grok and codex")
    for role in registry["roles"]:
        toml = root / CODEX_AGENT_DIR / f"{codex_agent_name(hosts, role)}.toml"
        if not toml.is_file():
            problems.append(f"Codex agent missing: {toml.relative_to(root)} (python3 scripts/render-role-agents.py)")
    for icon in ("composerIcon", "logo"):
        rel = hosts["codex"]["interface"].get(icon)
        if rel and not (root / rel).is_file():
            problems.append(f"Codex interface {icon} not found: {rel}")
    return problems
