#!/usr/bin/env python3
"""Host manifests and the host reference, generated from adapters/hosts.json + workflow/registry.json.

Called by `workflow.py render` (generated_files), so `render --check` and health-check catch drift.
Why each file looks the way it does is recorded in adapters/HOST-NOTES.md:
- no root plugin.json: Grok reads it before .grok-plugin/ and would lose the explicit agent list;
- explicit agent lists: Claude Code and Grok scan agents/ recursively (agent-sources/_lib, agent-sources/profiles are sources);
- Codex has its own marketplace file: `policy` is required there but unknown to Claude Code (--strict fails).
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HOSTS_FILE = "adapters/hosts.json"
CODEX_AGENT_DIR = "adapters/codex/agents"
KIMI_AGENT_DIR = "adapters/kimi/agents"


def load_hosts(root=ROOT):
    return json.loads((Path(root) / HOSTS_FILE).read_text(encoding="utf-8"))


def _json(value):
    return json.dumps(value, ensure_ascii=False, indent=2) + "\n"


def role_agent_files(registry):
    return [f"./agents/{role}.md" for role in registry["roles"]]


def codex_agent_name(hosts, role):
    return hosts["codex"]["agent_prefix"] + role


def kimi_agent_name(hosts, role):
    return hosts["kimi"]["agent_prefix"] + role


def _identity(plugin, *keys):
    return {k: plugin[k] for k in keys if k in plugin}


def zcode_manifest(hosts):
    p = hosts["plugin"]
    return {**_identity(p, "name", "version", "description", "description_i18n", "author", "keywords"),
            "skills": "skills", "commands": "commands", "agents": "agents"}


def claude_manifest(hosts, registry):
    # Claude Code and Grok share the format; both need the explicit list (recursive agents/ scan).
    p = hosts["plugin"]
    return {**_identity(p, "name", "version", "description", "author", "license", "repository", "keywords"),
            "agents": role_agent_files(registry)}


def kimi_manifest(hosts):
    p = hosts["plugin"]
    return {**_identity(p, "name", "version", "description", "author", "license", "keywords"),
            "skills": "./skills/", "commands": "./commands/", "agents": "./" + KIMI_AGENT_DIR + "/",
            "systemPrompt": "SDLC commands and packets use logical sdlc-workflow:<skill> names. "
                            "Invoke the discovered bare <skill> name with Skill, or Read its SKILL.md. "
                            "Use skills/sdlc/references/hosts.md for role dispatch and permission mapping."}


def claude_marketplace(hosts):
    p, m = hosts["plugin"], hosts["marketplace"]
    return {"name": m["name"], "owner": m["owner"], "description": m["description"],
            "plugins": [{"name": p["name"], "source": "./", "version": p["version"],
                         "description": p["description_i18n"]["en"], "category": m["category"]}]}


def codex_manifest(hosts):
    p = hosts["plugin"]
    return {**_identity(p, "name", "version", "description", "author", "license", "repository", "keywords"),
            "skills": "./skills/", "interface": hosts["codex"]["interface"]}


def codex_marketplace(hosts):
    p, m, c = hosts["plugin"], hosts["marketplace"], hosts["codex"]
    return {"name": m["name"], "interface": {"displayName": c["interface"]["displayName"]},
            "plugins": [{"name": p["name"], "source": {"source": "local", "path": "./"},
                         "policy": c["policy"], "category": c["category"]}]}


def render_host_reference(hosts, registry):
    rows = ["# Hosts (generated)", "",
            "<!-- GENERATED by scripts/workflow.py render from adapters/hosts.json and workflow/registry.json. -->", "",
            "One workflow supplies ZCode, Claude Code, Grok, Codex and Kimi Code; entry points and role/tool names differ by host. Packets and state "
            "always name the logical role `sdlc-workflow:<role>`; only the spawn call uses the host's type below. "
            "Identify the host from the tools you have (the host identity and its advertised role/tool catalog); "
            "when unsure, try the native role type first.", "",
            "| Host | Manifest | Commands | Spawn a hat as | Generic fallback | Invoke a procedure | Reviewer/qc read-only |",
            "|---|---|---|---|---|---|---|"]
    for h in hosts["hosts"]:
        rows.append(f"| {h['label']} | `{h['manifest']}` | {h['commands']} | `{h['role_type']}` | `{h['generic_type']}` "
                    f"| {h['skill_call']} | {h['read_only']} |")
    rows += ["",
             "## Spawning and fallback", "",
             "Check the dispatch tool schema first. When it has a role/type selector, spawn the native role type once. "
             "If the host reports an unknown type, spawn **once** as that host's generic "
             "type with the same packet; its first action reads `PLUGIN_ROOT/agents/<role>.md` and the primary SKILL.md. "
             "Record `host_spawn.<role>` with the host, the type tried and the fallback used. Never dispatch both forms. "
             "Codex and Kimi use project-linked prefixed roles. Check their links before falling back. "
             "For reviewer/qc, an unknown native role must **not** fall back to a writable generic agent. "
             "Use a fresh context with verified read-only tools/sandbox, or record review as blocked until the role "
             "is linked and the host restarted. A prompt-only write prohibition is not equivalent. Record the "
             "effective permissions and context isolation separately from the requested role; runtime overrides "
             "can change Codex sandbox settings. A read-only host fallback (for example Kimi `plan`) may be used "
             "only after verifying its effective tools, with the same review packet and full final report.", "",
             "### Codex dispatcher variants", "",
             "Some Codex runtimes expose `spawn_agent(agent_type=...)`; use the linked TOML role there. Others "
             "expose only `collaboration.spawn_agent(task_name, message, fork_turns)` with no type selector "
             "(observed with CLI 0.157.1). Do not invent an `agent_type` argument or treat `task_name` as a role "
             "selector. In that runtime, record `native_type_unavailable`, spawn once with `fork_turns: none` "
             "and the packet in `message`, and have the child read the generated Codex role TOML's instructions "
             "and primary SKILL.md. This is a prompt-bound fallback: the TOML sandbox is not applied. "
             "Reviewer/qc require an independently verified read-only parent/session inherited by the child, "
             "or a host facility that restricts the child before it runs. Otherwise leave review blocked. "
             "For producer roles, the fallback retains packet write scopes and normal execution observation.", "",
             "## Reference only", "",
             "Every host uses this plugin by reference to one source directory. Never run a command that copies it; "
             "a copy silently diverges from the source.", ""]
    rows += [f"- **{h['label']}**: {h['install']}." for h in hosts["hosts"]]
    rows += ["",
             "## PLUGIN_ROOT", "",
             "PLUGIN_ROOT is two directories above the **real path** of the running `SKILL.md` (the folder with "
             "`skills/`, `agents/`, `scripts/`). Resolve symlinks first (`realpath <SKILL.md>`): hosts reach the plugin "
             "through links, and Codex shows `<project>/.codex/skills/sdlc-workflow/<skill>/SKILL.md`, whose lexical parent is "
             "not the plugin. ZCode also exports `$ZCODE_PLUGIN_ROOT` to the shell; Claude Code (`CLAUDE_PLUGIN_ROOT`) "
             "and Grok (`GROK_PLUGIN_ROOT`) set theirs only for hooks and MCP servers. Pass the absolute PLUGIN_ROOT in "
             "every packet.", "",
             "## Commands on hosts without plugin commands", "",
             "Codex plugins carry skills only; Kimi project links expose skills rather than plugin commands. Invoke the command's skill and state the mode in the request; the skill "
             "treats an explicit `mode:` (or the command name, such as `/sdlc-product`) exactly like the command.", "",
             "| Command | Skill | Mode | Codex request (`$` or `/skills`) | Kimi project request |", "|---|---|---|---|---|"]
    for name, item in registry["commands"].items():
        rows.append(f"| `/{name}` | `sdlc-workflow:{item['skill']}` | `{item['mode']}` "
                    f"| `sdlc-workflow:{item['skill']}` + `mode: {item['mode']} <arguments>` "
                    f"| `/skill:{item['skill']} mode: {item['mode']} <arguments>` |")
    rows += ["", "## Role agents per host", "",
             "| Role | ZCode / Claude Code / Grok | Codex (linked) | Kimi (linked) | Read-only |", "|---|---|---|---|---|"]
    for role, meta in registry["roles"].items():
        rows.append(f"| {role} | `sdlc-workflow:{role}` | `{codex_agent_name(hosts, role)}` | `{kimi_agent_name(hosts, role)}` | {'yes' if meta['fresh'] else 'no'} |")
    return "\n".join(rows) + "\n"


def render_hosts(registry, root=ROOT):
    hosts = load_hosts(root)
    yield ".zcode-plugin/plugin.json", _json(zcode_manifest(hosts))
    yield ".claude-plugin/plugin.json", _json(claude_manifest(hosts, registry))
    yield ".claude-plugin/marketplace.json", _json(claude_marketplace(hosts))
    yield ".grok-plugin/plugin.json", _json(claude_manifest(hosts, registry))
    yield ".kimi-plugin/plugin.json", _json(kimi_manifest(hosts))
    yield ".codex-plugin/plugin.json", _json(codex_manifest(hosts))
    yield ".agents/plugins/marketplace.json", _json(codex_marketplace(hosts))
    yield "skills/sdlc/references/hosts.md", render_host_reference(hosts, registry)


def host_problems(registry, root=ROOT):
    """Structural rules the generated files cannot express by themselves."""
    root = Path(root)
    problems = []
    hosts = load_hosts(root)
    if (root / "plugin.json").exists():
        problems.append("plugin.json at the plugin root: Grok reads it before .grok-plugin/ and drops the explicit agent list")
    for rel in role_agent_files(registry):
        if not (root / rel).is_file():
            problems.append(f"listed agent missing: {rel}")
    if {h["id"] for h in hosts["hosts"]} != {"zcode", "claude", "grok", "codex", "kimi"}:
        problems.append("adapters/hosts.json hosts must describe zcode, claude, grok, codex and kimi")
    for role in registry["roles"]:
        toml = root / CODEX_AGENT_DIR / f"{codex_agent_name(hosts, role)}.toml"
        if not toml.is_file():
            problems.append(f"Codex agent missing: {toml.relative_to(root)} (python3 scripts/render-role-agents.py)")
    expected = {root / "agents" / f"{role}.md" for role in registry["roles"]}
    if set((root / "agents").rglob("*.md")) != expected:
        problems.append("agents/ must contain only rendered roles; keep sources in agent-sources/")
    for role in registry["roles"]:
        path = root / KIMI_AGENT_DIR / f"{kimi_agent_name(hosts, role)}.md"
        if not path.is_file():
            problems.append(f"Kimi agent missing: {path.relative_to(root)} (render-role-agents.py)")
    for icon in ("composerIcon", "logo"):
        rel = hosts["codex"]["interface"].get(icon)
        if rel and not (root / rel).is_file():
            problems.append(f"Codex interface {icon} not found: {rel}")
    return problems
